//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SysInventory.LogMessages.Models;

namespace SysInventory.LogMessages.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer : IIdentifiable
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> InactivedAt { get; set; }
        public System.Guid AddressFk { get; set; }
        public System.Guid AddressTypeFk { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AddressType AddressType { get; set; }
    }
}
