//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Runtime.CompilerServices;
using SysInventory.LogMessages.Annotations;
using SysInventory.LogMessages.Models;
using System;
using System.Collections.Generic;

namespace SysInventory.LogMessages.DataAccess.Ef
{
    public partial class Customer : IIdentifiable, INotifyPropertyChanged
    {
        private Address _address;
        private AddressType _addressType;
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> InactivedAt { get; set; }
        public System.Guid AddressFk { get; set; }
        public System.Guid AddressTypeFk { get; set; }
        public string CustomerNumber { get; set; }
        public string Website { get; set; }
        public string Password { get; set; }
        public virtual Address Address
        {
            get => _address;
            set
            {
                _address = value;
                OnPropertyChanged(nameof(Address));
            }
        }
        public virtual AddressType AddressType
        {
            get => _addressType;
            set
            {
                _addressType = value;
                OnPropertyChanged(nameof(AddressType));
            }
        }
        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
