//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysInventory.LogMessages.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEf
    {
        public System.Guid LogId { get; set; }
        public string Message { get; set; }
        public System.Guid DeviceFk { get; set; }
        public int Severity { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool Confirmed { get; set; }
    }
}
