//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysInventory.LogMessages.DataAccess.Ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SysInventoryEntities : DbContext
    {
        public SysInventoryEntities()
            : base("name=SysInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LocationEf> LocationEfs { get; set; }
        public virtual DbSet<v_logentries> v_logentries { get; set; }
        public virtual DbSet<LogEf> LogEfs { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumbers { get; set; }
        public virtual DbSet<PhoneType> PhoneTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContactPerson> ContactPersons { get; set; }
    
        public virtual int LogClear(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LogClear", idParameter);
        }
    
        public virtual int LogMessageAdd(string podName, string hostname, Nullable<int> lvl, string msg)
        {
            var podNameParameter = podName != null ?
                new ObjectParameter("podName", podName) :
                new ObjectParameter("podName", typeof(string));
    
            var hostnameParameter = hostname != null ?
                new ObjectParameter("hostname", hostname) :
                new ObjectParameter("hostname", typeof(string));
    
            var lvlParameter = lvl.HasValue ?
                new ObjectParameter("lvl", lvl) :
                new ObjectParameter("lvl", typeof(int));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LogMessageAdd", podNameParameter, hostnameParameter, lvlParameter, msgParameter);
        }
    }
}
