//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysInventory.LogMessages.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindowFunction
    {
        public string Category { get; set; }
        public string YOY { get; set; }
        public Nullable<decimal> C2020_Q4 { get; set; }
        public Nullable<decimal> C2020_Q3 { get; set; }
        public Nullable<decimal> C2020_Q2 { get; set; }
        public Nullable<decimal> C2020_Q1 { get; set; }
        public Nullable<decimal> C2019_Q4 { get; set; }
        public Nullable<decimal> C2019_Q3 { get; set; }
        public Nullable<decimal> C2019_Q2 { get; set; }
        public Nullable<decimal> C2019_Q1 { get; set; }
        public Nullable<decimal> C2018_Q4 { get; set; }
        public Nullable<decimal> C2018_Q3 { get; set; }
        public Nullable<decimal> C2018_Q2 { get; set; }
        public Nullable<decimal> C2018_Q1 { get; set; }
    }
}
